version: '3.9'
services:
 #
 #db:
  #image: mysql:8.0
  #environment:
    #MYSQL_ROOT_PASSWORD: password
    #MYSQL_USER: user
    #MYSQL_PASSWORD: 1234
    #MYSQL_DATABASE: test3_db
  #$volumes:
   # - mysql-data:/var/lib/mysql
  #$ports:
    #- "4306:3306"
  # コメントアウトする場合は以下を追加
  # environment:
  #   - ENVIRONMENT=production
  # ports:
  #   - "4306:3306"

  app:
    build: .
        # command: bundle exec puma -C config/puma.rbローカルと本番切り替え
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/test3
      - public-data:/test3/public
      - tmp-data:/test3/tmp
      - log-data:/test3/log
    networks:
      - test3-network
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/test3/public
      - tmp-data:/test3/tmp
    ports:
      - 80:80
    networks:
      - test3-network
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
networks:
  test3-network:
    external: true