version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: test3_db
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - public-data:/test3
      - tmp-data:/test3/tmp
      - log-data:/test3/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/test3/public
      - tmp-data:/test3/tmp
    ports:
      - 80:80

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
